name: Deploy with Docker Compose

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Create .env file for Compose
        run: |
          echo "DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}" > .env

      - name: Run Docker Compose
        run: |
          docker-compose up -d

      - name: Show Running Containers
        run: |
          docker ps

      - name: Wait and Test API
        run: |
          sleep 20
          curl -f http://localhost:8000/docs || exit 1

      - name: Streamlit Health Check
        run: |
          curl -f http://localhost:8501 || exit 1
