name: Deploy with Docker Compose

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Create .env file for Compose
        run: |
          echo "DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}" > .env

      - name: Start Docker Compose services
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for services to be healthy
        run: |
          for service in streamlit api prometheus grafana; do
            echo "Waiting for $service to become healthy..."
            for i in {1..30}; do
              status=$(docker inspect --format='{{json .State.Health.Status}}' $(docker-compose ps -q $service))
              echo "$service status: $status"
              if [ "$status" == '"healthy"' ]; then
                echo "$service is healthy."
                break
              fi
              if [ $i -eq 30 ]; then
                echo "$service failed to become healthy. Dumping logs:"
                docker-compose logs $service
                exit 1
              fi
              sleep 5
            done
          done

      - name: List running containers
        run: docker ps -a

      - name: Dump Docker Compose logs
        if: always()
        run: docker-compose logs