name: Build and Push Docker Images (API, UI)

on:
  push:
    branches: [main]

env:
  REGISTRY: docker.io
  USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
  MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}

jobs:
  build-push-ui-api:
    needs: build-push-mlmodel  # wait for model container to be built
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [streamlit, api]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push ${{ matrix.service }} Image
        run: |
          docker build -t $REGISTRY/$USERNAME/loan-${{ matrix.service }} -f docker/${{ matrix.service }}/Dockerfile .
          docker push $REGISTRY/$USERNAME/loan-${{ matrix.service }}