name: Build and Push Docker Images

on:
  push:
    branches: [main]

env:
  REGISTRY: docker.io
  USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

jobs:

  ### 1. Build & Push MLflow Model Docker Image
  build-push-mlmodel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install MLflow
        run: pip install mlflow

      - name: Build MLflow Docker Image from Local Artifacts
        run: |
          mlflow models build-docker \
            --model-uri ./ml/downloaded_artifacts/model \
            --name revamp-loan-approval

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag & Push MLflow Model Image
        run: |
          docker tag revamp-loan-approval $REGISTRY/$USERNAME/loan-mlmodel:latest
          docker push $REGISTRY/$USERNAME/loan-mlmodel:latest

  ### 2. Build & Push API + Streamlit
  build-push-ui-api:
    needs: build-push-mlmodel  # wait for model container to be built
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [streamlit, api]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push ${{ matrix.service }} Image
        run: |
          docker build -t $REGISTRY/$USERNAME/loan-${{ matrix.service }} -f docker/${{ matrix.service }}/Dockerfile .
          docker push $REGISTRY/$USERNAME/loan-${{ matrix.service }}
