name: Build and Push ML Docker Images

on:
  push:
    branches: [main]

env:
  REGISTRY: docker.io
  USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }} #
  MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
  MLFLOW_RUN_ID: ${{ secrets.MLFLOW_RUN_ID }}

jobs:
  build-push-mlmodel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install MLflow
        run: pip install mlflow python-dotenv

      - name: Authenticate to Dagshub
        run: |
          echo "machine dagshub.com login $DAGSHUB_USERNAME password $DAGSHUB_TOKEN" > ~/.netrc

      - name: Download MLflow model artifacts from DagsHub
        run: |
          mkdir -p ml/scripts
          cat <<EOF > ml/scripts/download_artifacts.py
          import mlflow
          from mlflow.tracking import MlflowClient
          import os

          mlflow.set_tracking_uri(os.environ["MLFLOW_TRACKING_URI"])
          run_id = os.environ["MLFLOW_RUN_ID"]
          client = MlflowClient()

          dst_path = "ml/my-downloaded-artifacts"
          os.makedirs(dst_path, exist_ok=True)
          client.download_artifacts(run_id, path="", dst_path=dst_path)
          EOF

          python ml/scripts/download_artifacts.py

      - name: Build MLflow Docker Image from Registry
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        run: |
          mlflow models build-docker \
            --model-uri "models:/revamp-loan-approval-model/Production" \
            --name revamp-loan-approval

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag & Push MLflow Model Image
        run: |
          docker tag revamp-loan-approval $REGISTRY/$USERNAME/loan-mlmodel:latest
          docker push $REGISTRY/$USERNAME/loan-mlmodel:latest

  build-push-ui-api:
    needs: build-push-mlmodel  # wait for model container to be built
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [streamlit, api]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push ${{ matrix.service }} Image
        run: |
          docker build -t $REGISTRY/$USERNAME/loan-${{ matrix.service }} -f docker/${{ matrix.service }}/Dockerfile .
          docker push $REGISTRY/$USERNAME/loan-${{ matrix.service }}
