name: Build and Push Docker Images

on:
  push:
    branches: [main]

env:
  REGISTRY: docker.io
  USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:

  ### 1. Build & Push MLflow Model Docker Image
  build-push-mlmodel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          pip install mlflow scikit-learn pandas

      - name: Set MLflow Tracking URI
        run: |
          echo "MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=${{ secrets.MLFLOW_TRACKING_USERNAME }}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.MLFLOW_TRACKING_PASSWORD }}" >> $GITHUB_ENV

      - name: Get Latest MLflow Run ID
        id: get_run
        run: |
          RUN_ID=$(mlflow runs list --order-by start_time DESC --max-results 1 | tail -n +2 | awk '{print $1}')
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      - name: Build Docker Model
        shell: bash -l {0}
        env:
          RUN_ID: ${{ env.RUN_ID }}
        run: |
          echo "RUN_ID from env: $RUN_ID"
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "revamp-loan-approval" 

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag revamp-loan-approval ${{ secrets.DOCKER_HUB_USERNAME }}/revamp-loan-approval:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/revamp-loan-approval:latest

  ### 2. Build & Push API + Streamlit
  build-push-ui-api:
    needs: build-push-mlmodel  # wait for model container to be built
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [streamlit, api]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push ${{ matrix.service }} Image
        run: |
          docker build -t $REGISTRY/$USERNAME/loan-${{ matrix.service }} -f docker/${{ matrix.service }}/Dockerfile .
          docker push $REGISTRY/$USERNAME/loan-${{ matrix.service }}
